# Generated by Django 3.2 on 2021-04-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('anddress', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('excerpt', models.TextField(max_length=300)),
                ('pictrure', models.ImageField(upload_to='Uni_picture')),
                ('majors', models.CharField(max_length=100)),
            ],
        ),
    ]
